### ISSUE TITLE
ModuleNotFoundError: No module named 'humanize'

### ISSUE THREAD

**Issue by seapagan** [James4Ever0/vignore#1]
Using `pip`, `pipx` or `uv tool` gives the below error on running `vignore`:

Traceback (most recent call last):
  File "/home/seapagan/.pyenv/versions/3.12.6/bin/vignore", line 5, in <module>
    from vignore.cli import main
  File "/home/seapagan/.pyenv/versions/3.12.6/lib/python3.12/site-packages/vignore/__init__.py", line 16, in <module>
    import humanize
ModuleNotFoundError: No module named 'humanize'

Looks like `humanize` needs to be added to the deps - if I `pip install` / `pipx inject` `humanize` then it works.

**Comment by James4Ever0** [comment]
Code has changed. Will be fixed in the next version.

**Comment by James4Ever0** [comment]
Fixed in [v1.0.5](https://pypi.org/project/vignore/1.0.5/)
